### ISSUE TITLE
Цвета Style_DOS

### ISSUE THREAD

**Issue by teenbull** [narmiel/UrqW#10]
Сейчас вебурка вообще игнорирует цвета, включающие цвет фона символа (больше 15).
Скриншоты color.qst:
http://nyah.ru/scr/456c8edbd26bacc65c56321973bb.png

color.qst:
:0
Style_DOS_FillEol=0
Style_DOS_TextColor=7
pln == Палитра ==
pln <цвет>+16*<фон>
i=0
:loopi
j=0
:loopj
Style_DOS_TextColor=i+16*j
;p #i$,#j$
if Style_DOS_TextColor<10 then p ##32$
if Style_DOS_TextColor<100 then p ##32$
p ##32$#Style_DOS_TextColor$;
j=j+1
if j<16 then goto loopj
i=i+1
pln
if i<16 then goto loopi
;Style_DOS_ButtonColor=25
Style_DOS_TextColor=7
Style_DOS_ButtonColor=8
Style_DOS_CursorColor=11
btn 0,палитра
end

Даже если такие цвета не поддерживаются полностью юзер должен иметь возможность хотя бы прочитать текст. А то получается такое: http://nyah.ru/scr/095a06e0b699e4e1a9d23dc74bb7.png

**Comment by narmiel** [comment]
https://github.com/narmiel/UrqW/commit/be1f19928c7473e6e0854d7b3760f1a408047254
