### ISSUE TITLE
предмет с use опцией всегда вываливает пункт меню - осмотреть

### ISSUE THREAD

**Issue by AjentaArrow** [narmiel/UrqW#12]
Двадцать предметов с юз опцией будут выдавать те же двадцать посомтреть по одному у каждого. Это лишние пункты и смотрится сие очень странно. Хорошо бы переделать так, что если у предмета только один юз без названия, то не вываливался никакой пункт меню, а обрабатывался бы просто сразу клик на предмет. А если у предмета есть название у опции юза или у предмета два юза, то пункт меню показывался бы, возможно не один.

**Comment by narmiel** [comment]
https://github.com/narmiel/UrqW/commit/7d16e569d5b2d1c297ff21c7129548604cc26b18
