### ISSUE TITLE
Не могу играть в Остров Хйфич

### ISSUE THREAD

**Issue by Lookdream123** [narmiel/UrqW#17]
Вместо слов игра выдает какие то символы непонятные. Что делать, очень хочется поиграть. 
 
![18ad9-clip-21kb](https://cloud.githubusercontent.com/assets/25127182/21959555/c1cb3684-dadb-11e6-9ea0-ec911881bd81.png)

**Comment by narmiel** [comment]
Я так понимаю вопрос относится к версии размещенной на сервере Горафа (http://pavlenko.biz/urq/#99999)? Да, я вижу там эту проблему, но это не относится к интерпретатору UrqW, все вопросы к Горафу. Можно поиграть в версию которую выкладывал у себя я, она работает (narmiel.github.io/UrqW/#99999). Но возможно она уже устарела.
