### ISSUE TITLE
Странно работает pause

### ISSUE THREAD

**Issue by xlomid** [narmiel/UrqW#24]
Я в курсе, что пауза прерывается при любом действии пользователя -- но странно, что последующие вызовы паузы при этом ускоряются. Простой пример:

```
:init1
cd=20
:refresh
cls
pln #cd$
pln [[click here!|click]]
pause 1000
cd=cd-1
goto refresh
end
:click
pln OK
goto refresh
end
```
Стоит мне кликнуть дважды или трижды -- и секундный счётчик начинает проматываться по несколько "секунд" за раз. Странно же?

**Comment by narmiel** [comment]
переписано и работает нормально в версии 2.0
