### ISSUE TITLE
Anykey не возвращает коды некоторых клавиш

### ISSUE THREAD

**Issue by xlomid** [narmiel/UrqW#25]
Команда anykey x возвращает 0, если игрок нажимает на стрелки, Enter, Esc или Backspace. А вот буквы, цифры и пробел работают без проблем.

Можно сделать так, чтобы игра могла различать нажатия на эти клавиши (хотя бы стрелки и Enter как наиболее часто используемые)?

**Comment by narmiel** [comment]
Сейчас anykey возвращает номер нажатого символа в таблице unicode, то есть английская раскладка и русская возвращают разные значения. Можно возвращать код нажатой клавиши, как тут http://keycode.info , думаю так будет правильнее. Тогда и стрелочки/интер заработают. Как было в досурке?

**Comment by xlomid** [comment]
Я всегда думал, что в досурке возвращались ASCII-коды. Но гугл сообщил мне, что у тех же стрелок ASCII-кодов нет. А досурка вполне себе возвращала коды стрелок (вверх-72, вниз-80, влево-75, вправо-77). Досурка возвращала даже Ctrl (29), Alt (56) и Shift (42). Видимо, это досовские сканкоды? Не думаю, что вебурке нужно под это подстраиваться (разве что в досурк-режиме для совместимости), но возвращать код клавиши, наверное, лучше, чем номер символа.

**Comment by narmiel** [comment]
dd8559b0b1be4d2a95663893e67e0b969d3dfc68 сделан возврат кода клавиши вместо кода символа, по событию keyDown вместо keyPress
