### ISSUE TITLE
Не работает instr tokens_delim=char

### ISSUE THREAD

**Issue by xlomid** [narmiel/UrqW#26]
В досурке у переменной tokens_delim было специальное значение "char" (instr tokens_delim=char), при котором команда tokens разбивала строку на отдельные символы (т.е. "A,B" разбивалась бы на "A", ",", "B").

Было бы чудесно, если бы это значение понимала и UrqW.

**Comment by narmiel** [comment]
fixed e6424de15baf39153ace7486a08c7a7b5907eb79
