### ISSUE TITLE
Починить работу окон загрузки/сохранения

### ISSUE THREAD

**Issue by hogart** [narmiel/UrqW#34]
- [ ] не переключаются окна нормально
- [ ] нет возврата к игре по кнопке

**Comment by narmiel** [comment]
там два бага:
1 после сохранения/загрузки нет возврата к экрану игры
2 не работает кнопка Вернуться к игре

**Comment by narmiel** [comment]
7b0681527cd788174c4d34bf1e4289af6ae0fb4b
