### ISSUE TITLE
Загрузка игр по get-ссылкам

### ISSUE THREAD

**Issue by realsonic** [narmiel/UrqW#6]
Загрузка игр по get-ссылкам, например: http://narmiel.github.io/UrqW/?game=http://urq.plut.info/system/files/MOU_NEW1.2.qsz

**Comment by narmiel** [comment]
У меня же нет сервера, это жс. Я могу получить ссылку, но на js невозможно получить файл с удалённого сервера. Если только сервер не отправляет специальные заголовки с разрешением на такое.

Для того чтобы это выполнить нужен сервер с серьёзным (!) трафиком где я смогу разместить php скрипт. И то, это будет работать только с моей онлайн версии и ни у кого больше.

**Comment by realsonic** [comment]
@narmiel а разве нельзя это сделать через AJAX? http://stackoverflow.com/a/13329900/1035476

**Comment by narmiel** [comment]
Со своего сервера можно аяксом, с любых нет.

**Comment by realsonic** [comment]
@narmiel тогда такой вариант: конфигурирование реестра своих игр, чтобы можно было разместить ОнлайнУРКу на своей страничке со своими играми. Так можно?

**Comment by narmiel** [comment]
@realsonic  Как понять конфигурирование реестра своих игр? Сервера нет, можно в хтмл index файле "сконфигурировать" "реестр", положив свои игры в папку quests/ (как те что лежат там для примера). Или ты хочешь json файл с конфигураций? Так тоже можно, было в планах но не приоритетно.

**Comment by realsonic** [comment]
@narmiel да, что-то максимально простое для настройки - json или xml, например.

**Comment by narmiel** [comment]
json файл games.json был добавлен
