### ISSUE TITLE
Не работает btn денег = 14 & goto castle, Идти к замку

### ISSUE THREAD

**Issue by AjentaArrow** [narmiel/UrqW#7]
Кнопка вообще ненажимается и никуда не переходит.

:nachalo1
cls
pln <center><h2>Выберите своего персонажа</h2></center>
pln
if шляпы_надеты = 1 then
_ pln <center><table><tr><td><img src="1.png"></td><td><img src="2.png"></td><td><img src="3.png"></td></tr></table></center>
if шляпы_надеты = 0 then
_ pln <center><table><tr><td><img src="1a.png"></td><td><img src="2a.png"></td><td><img src="3a.png"></td></tr></table></center>
pln
pln <b>Человек</b> - эта ведьмочка обычный человек, что во множестве населяют планету. Все волшебные расы относятся к людям нейтрально.
pln
pln <b>Эльф</b> - видимо, отцом этой ведьмочки был эльф. Эльфов в этом мире осталось не так много, но они и не редки. Многие волшебные расы относятся к эльфам положительно, но есть и те, что их ненавидят.
pln
pln <b>Демон</b> - кто-то из предков этой ведьмочки был демоном. Демоны стречаются очень редко. Многие считают, что эта раса совсем вымерла. Волшебные расы в основном недолюбливают демонов, но некоторые особо древние привыкли считать их чем-то вроде высших, и поклоняться наравне с божествами.
pln 
if шляпы_надеты = 1 then btn шляпы_надеты = 0 & goto nachalo1, Снять шляпы
if шляпы_надеты = 0 then btn шляпы_надеты = 1 & goto nachalo1, Одеть шляпы
btn раса = "человек" & goto домик_внутри, Выбрать человека
btn раса = "эльф" & goto домик_внутри, Выбрать эльфийку
btn раса = "демон" & goto домик_внутри, Выбрать демонеску

end

**Comment by narmiel** [comment]
Кавычки всё запороли ) Поправлено этим коммитом. https://github.com/narmiel/UrqW/commit/f002aa4842b7443232f113695c5af28461f192db Проверй
